In [1]:
from tensor import *
import numpy as np

In [2]:
x = Tensor(np.array([[1., 1.], [1., 1.]]), requires_grad = True); x.value

array([[1., 1.],
       [1., 1.]])

In [3]:
y = x + 2; y.value

array([[3., 3.],
       [3., 3.]])

In [4]:
z = y * y * 3

In [5]:
out = z.mean(); out.value

array([[27.]])

In [6]:
out.backwards()

[[0.5 0.5]
 [0.5 0.5]]


In [7]:
z.grad

array([[0.5, 0.5],
       [0.5, 0.5]])

In [8]:
x.grad

array([[4.5, 4.5],
       [4.5, 4.5]])